name: Staging to VPS

on:
  push:
    tags:
    - stage-*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v4
      - name: Copy Docker file
        run: cp ${{ github.workspace }}/docker-deploy/Dockerfile ${{ github.workspace }}/Dockerfile
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            juanmurielc/logisticsanddeliveries_webapi:${{ github.ref_name }}
            juanmurielc/logisticsanddeliveries_webapi:${{ github.sha }}
